work_dir: ./work_dir/p2a
model_saved_name: CTR_GCN

# feeder
feeder: feeders.my_feeder.Feeder
train_feeder_args:
  data_path: ../dataset/2024-p2a/2s-AGCN+MSG3D-fomat/p2a/v1+v2/2024-6-14-14-class-128/train_data_joint.npy
  label_path: ../dataset/2024-p2a/2s-AGCN+MSG3D-fomat/p2a/v1+v2/2024-6-14-14-class-128/train_label.pkl
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [ 0.5, 1 ]
  vel: False
  bone: False

test_feeder_args:
  data_path: ../dataset/2024-p2a/2s-AGCN+MSG3D-fomat/p2a/v1+v2/2024-6-14-14-class-128/val_data_joint.npy
  label_path: ../dataset/2024-p2a/2s-AGCN+MSG3D-fomat/p2a/v1+v2/2024-6-14-14-class-128/val_label.pkl
  split: test
  window_size: 64
  p_interval: [ 0.95 ]
  vel: False
  bone: False
  debug: False

# model
model: model.ctrgcn.Model
model_args:
  num_class: 14
  num_point: 17
  num_person: 1
  graph: graph.pingpong_coco.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [ 35, 55 ]
warm_up_epoch: 5

# training
device: [ 2 ]
batch_size: 64
test_batch_size: 64
num_epoch: 65
nesterov: True
save_score: True